apiVersion: v1
kind: Service
metadata:
  labels:
    name: quarkus-native-todo-svc
  name: quarkus-native-todo-svc
spec:
  ports:
  - port: 8080
    #nodePort: 30203
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkusnative-todo
    version: v1
  type: ClusterIP
status:
  loadBalancer: {}
