apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot-todo-svc
  name: springboot-todo-svc
spec:
  ports:
  - port: 8080
    #nodePort: 30201
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-todo
    version: v3.1.0
  type: ClusterIP
status:
  loadBalancer: {}

