apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkusjvm-todo
    version: v2.2
    app.openshift.io/runtime: quarkus
  name: quarkus-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkusjvm-todo
      version: v2.2
  strategy: {}
  template:
    metadata:
      labels:
        app: quarkusjvm-todo
        version: v2.2
    spec:
      containers:
      - image: quay.io/naveenkendyala/quarkus-demo-quarkusjvm-todo:v2.2
        name: quarkusjvm-todo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        envFrom:
        - configMapRef:
            name: quarkus-demo-quarkusjvm-todo-cm
        - secretRef:
            name: quarkus-demo-quarkusjvm-todo-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "175Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
              port: 8080
              path: /q/health/live
          initialDelaySeconds: 12
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
status: {}
