apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
    version: v2
  name: quarkus-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: todo
        version: v2
    spec:
      containers:
      - image: quay.io/naveenkendyala/quarkus-demo-quarkusjvm:v1
        name: quarkus-jvm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        envFrom:
        - configMapRef:
            name: istio-demo-recommendation-v2-cm
        - secretRef:
            name: istio-demo-recommendation-v2-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "175Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
              port: 8080
              path: /health/live
          initialDelaySeconds: 12
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
status: {}
